name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: sudo apt-get install -y python3 python3-pip cmake gcc clang make git golang && pip3 install conan

  build:
    runs-on: ubuntu-latest
    needs: base

    steps:
    - name: build
      run: make

    - name: ctest
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose

